version: '3.8'

services:
  docusaurus:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: base-library-docs
    restart: unless-stopped
    ports:
      - "3000:3000"
    networks:
      - docusaurus-net
    environment:
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  nginx:
    image: nginx:alpine
    container_name: docusaurus-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - docusaurus
    networks:
      - docusaurus-net

networks:
  docusaurus-net:
    driver: bridge
